baseURL = ""
languageCode = "en-us"
title = "Sheldon Talk"
rssLimit = 20
minify = false

[Author]
  name = "Sheldon Chen"
  email = "sheldon.ziping.chen@gmail.com"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]
