name: Deploy Hugo # 任君喜欢

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Building..."
        uses: reuixiy/hugo-deploy@v1
        env:
          DEPLOY_REPO: sheldonzipingchen/sheldonzipingchen.github.io
          DEPLOY_BRANCH: build
          DEPLOY_KEY: ${{ secrets.personal_token }}
          # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          TZ: Asia/Shanghai
